general.import = ["~/.config/alacritty/catppuccin-macchiato.toml"]

[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10
startup_mode = "Fullscreen"

decorations = "none"

[font]
normal.family = "JetBrainsMono Nerd Font"
size = 12

[colors.cursor]
text = "CellBackground"
cursor = "#b4befe"  # lavender from catppuccin
